# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b34d2e9dd938ed2f1fcd482353170e455f30db21e9b5d04b44175c70999f4d573f7d212fbf370e3bda453b298ff599cc94d7ba5a7591bc3bea3f83ed16b27d

test:
  secret_key_base: c3e4d077421124adb41e79b1112c7f3197b5569a00a638a02299aec2ac91822f46ec466068dd89c4193a5e97c1a81126a228a518f19fc29190db47ea91a6fe02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
